name: Backend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3    # Added the missing 'uses' key
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
